### ISSUE TITLE
Updating problem

### ISSUE THREAD

**Issue by jgarbi** [kelias/Jarloo.Sojurn#13] opened 2017-11-07 08:11 UTC
I found that I have problems updating a few series : Narcos, ShutEye and House of Cards haven't been updated for 7 days. If I remove them, I can't add them anymore. They're listed when I search for them, but I can't add them. 
Any ideas ?

**Comment by kelias** [comment] 2017-11-07 14:04
The problem is how Netflix is returning the Country Code. The used to return a null webchannel node now they return one, but set country=null.

Fix is in the TvMazeInformationProvider.GetCountryCode() method. 

I checked it in, so you can do a checkout and build and it should work again for you. I have NOT done a release with this fix yet.

**Closed by kelias** 2017-11-07 14:04 UTC
